# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 20 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jskherman
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          commits_authoring: jskherman,68434444+jskherman@users.noreply.github.com
          config_timezone: Asia/Manila
          # plugin_16personalities: yes
          # plugin_16personalities_scores: yes
          # plugin_16personalities_sections: personality, profile, traits
          # plugin_16personalities_url: "https://www.16personalities.com/profiles/672b5e6d1fea7"
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # plugin_fortune: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_skipped: brain2
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: javascript, typescript
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_delay: 5
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # plugin_music: yes
          # plugin_music_limit: 4
          # plugin_music_mode: recent
          # plugin_music_played_at: yes
          # plugin_music_provider: lastfm
          # plugin_music_time_range: short
          # plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          # plugin_music_top_type: tracks
          # plugin_music_user: jsk_herman
          # plugin_notable: yes
          # plugin_notable_from: organization
          # plugin_notable_types: commit
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          # plugin_repositories: yes
          # plugin_repositories_order: featured, pinned, starred, random
          # plugin_repositories_starred: 4
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me?
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: jskherman

